spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuration for DDL update
spring.jpa.hibernate.ddl-auto=update

# Custom property for environment check
app.environment=prod

server.port=8081

# Enable H2 Console for debugging at /h2-console
spring.h2.console.enabled=true